name: Test
on: [push,pull_request]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install Deps
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Run Test
        run: npm run test:ci
      - name: Run Lint
        run: npm run lint